
<table>
<tr>
<th>Name</th>
<th>Catagory</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->albums as $album) : ?>
<tr>
<td><?php echo $this->escape($album->name);?></td>
<td><?php echo $this->escape($album->catagory);?></td>
<td>

   
<!--<a href="/member/edituseralbum?code=<?php echo $album->ID ?>">Edit</a>--> 
<!--<a href="/member/deletealbum?code=<?php echo $album->ID ?>" onclick ="return confirm('Are you sure?');">Delete</a>-->
<a href="/song/viewsongs?code=<?php echo $album->ID ?>">View Songs </a>
</td>
</tr>
<?php endforeach; ?>
</table> 

