<link href="/css/bootstrap-fileupload.css" rel="stylesheet">
<script src="/js/bootstrap-fileupload.js"></script>

<div class="frame">
    <div class="left">
        <form action="/member/uploadprofileimage" method="post" enctype="multipart/form-data">
            <div class="fileupload fileupload-new" data-provides="fileupload">
                <div class="fileupload-new thumbnail btn-file" style="width: 190px; height: 150px;"><input style="width: 190px; height: 150px;" type="file" name="pro_img" />
                    <?php if(!empty($this->info[0]['profile_pic'])):?>
                    <img src="<?= $this->info[0]['profile_pic'] ?>" />
                    <?php else :?>                   
                    <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=no+image" />
                    <?php endif; ?>
                </div>
                <div class="fileupload-preview fileupload-exists thumbnail" style="max-width: 190px; max-height: 150px; line-height: 20px;"></div>
                <div class="img_btn">
                    <a href="#" class="btn fileupload-exists" data-dismiss="fileupload"><i class="icon icon-trash"></i>&nbsp;Remove</a>
                    <button type="submit" class="btn btn-success fileupload-exists"><i class="icon icon-plus icon-white"></i>&nbsp;Upload</button>
                </div>
            </div>
        </form>

        <div class="profile_image">
            <p class="text-center" style="color: #0088CC"><?= $this->myname ?></p>
            <hr>
            Major : Undecided <br>          
            Year  : Junior <br>

            <a href="/pm/inbox?user_id=<?= $this->myinfo->id ?>"><i class="icon icon-envelope"></i>&nbsp;&nbsp;Inbox</a><br>            
            <a href="/setting/edit_info"><i class="icon icon-wrench"></i>&nbsp;&nbsp;Setting</a><br>

        </div>
    </div>

    <div class="span6">
        <form action="/member/mystatus" method="post">    
            <p class="lead page_msg">Say something to Baruchian!</p>           
            <input type="hidden" value="<?= $this->myinfo->id ?>" name="wall_owner" />           
            <textarea rows="3" class="post_status" name="status_post"></textarea>
            <div class="post_bottom">
                <button class="btn btn-block right" type="submit">Share</button>
            </div>
        </form>
        <table>
            <?php foreach ($this->mystatus_post as $posts): ?>
                <tr>
                <div>
                    <?php if ($posts['poster'] != $posts['wall_owner']): ?>
                        <p>
                            <a href="/member/profile/?id=<?= $posts['poster'] ?>"><img class="wall_img" src="<?= $posts['profile_pic'] ?>"><?= $posts['first_name'] ?>&nbsp;<?= $posts['last_name'] ?></a> <span class="arrow">&raquo;</span>
                            <a href="/member/profile/?id=<?= $posts['wall_owner'] ?>"><?= $posts['ownerfname'] ?>&nbsp;<?= $posts['ownerlname'] ?></a>
                        </p>
                    <?php else : ?>
                        <p><a href="/member/profile/?id=<?= $posts['poster'] ?>"><img class="wall_img" src="<?= $posts['ownerprofilepic'] ?>"><?= $posts['first_name'] ?>&nbsp;<?= $posts['last_name'] ?></a></p>
                    <?php endif; ?>
                    <p class="post"><?= stripslashes($posts['post']) ?></p>
                    <span class="time">
                        Posted On <?= date("jS \ F Y h:i:s A e", $posts['created']) ?>
                    </span>
                </div>
                <div style="clear: both"></div>
                <hr>   
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
<div style="clear: both"></div>

