
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Baruch Stance</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Le styles -->
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/college.css" rel="stylesheet">
        <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
        <style type="text/css">
            body {
                padding-top: 20px;
                padding-bottom: 40px;
            }

            /* Custom container */
            .container-narrow {
                margin: 0 auto;
                max-width: 700px;
            }
            .container-narrow > hr {
                margin: 30px 0;
            }

            /* Main marketing message and sign up button */
            .jumbotron {
                margin: 60px 0;
                text-align: center;
            }
            .jumbotron h1 {
                font-size: 72px;
                line-height: 1;
            }
            .jumbotron .btn {
                font-size: 21px;
                padding: 14px 24px;
            }

            /* Supporting marketing content */
            .marketing {
                margin: 60px 0;
            }
            .marketing p + h4 {
                margin-top: 28px;
            }
        </style>
        
        <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="../assets/js/html5shiv.js"></script>
        <![endif]-->

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="../assets/ico/favicon.png">
    </head>

    <body>

        <div class="container-narrow">
            <?php $auth = Zend_Auth::getInstance();
            if ($auth->hasIdentity()):
                ?>
                <div class="masthead">
                    <ul class="nav nav-pills pull-right">                         
                        <li class="<?= $this->mainactive ?>"><a href="/main/listposts">Home</a></li>                            
                        <li class="<?= $this->memberactive ?>"><a class="log_in" href="/member/profile">Profile</a></li>                        
                        <li class="dropdown">
                            <a class="dropdown-toggle <?= $this->memberactive ?>" data-toggle="dropdown" href="/member/profile">
                                Account
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="/member/private_message"><i class="icon icon-envelope"></i>&nbsp;&nbsp;Inbox</a></li>
                                <li><a href="/member/setting"><i class="icon icon-wrench"></i>&nbsp;&nbsp;Setting</a></li>
                                <li><a href="/index/logout"><i class="icon icon-off"></i>&nbsp;&nbsp;log out</a></li>
                            </ul>
                        </li>
                    </ul>
                    <h3 class="muted" style="color:#0088CC"><a style="text-decoration: none" href="/index">Baruch Stance</a></h3>
                </div>
<?php else : ?>
                <div class="masthead">
                    <ul class="nav nav-pills pull-right">
                        <li class="active"><a href="/index">Home</a></li>
                        <li class=""><a class="log_in" href="/index/signin">Sign In</a></li>
                        <li class=""><a href="/index/signup">Sign Up</a></li>
                    </ul>
                    <h3 class="muted" style="color:#0088CC"><a style="text-decoration: none" href="/index">Baruch Stance</a></h3>
                </div>
<?php endif; ?>
            <hr>

<?php echo $this->layout()->content ?> 

            <hr>

            <div class="footer">
                <p>&copy; Company 2013</p>
            </div>

        </div> <!-- /container -->

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="/js/jquery.js"></script>
        <script src="/js/bootstrap.js"></script>
        <script src="/js/bootstrap.min.js"></script>
        <script>
            $(document).ready(function(){
                $('.dropdown-toggle').dropdown();
            })
        </script>
    </body>
</html>
